eventauth.go, eventauth_test.go, eventcontent.go
This is equivalent to `StateNeededForAuth([]Event)` but operates on an `EventBuilder`
instead. Add tests to assert equivalence.
=> Add StateNeededForEventBuilder

event.go
Else you get:
```
json: error calling MarshalJSON for type gomatrixserverlib.rawJSON: unexpected end of JSON input
```
=> Allow callers to not have called Builder.SetUnsigned and still Build() the event

event.go, eventauth.go
Helper functions are designed to map easily between StateNeeded,
StateKeyTuples and []EventReference (auth_events).
=> Add StateKeyTuple type. Add helper functions for auth.

client.go, keyring.go, keyring_test.go, keys.go, signing.go, timestamp.go
This implements the logic in https://github.com/matrix-org/synapse/blob/master/synapse/crypto/keyring.py for checking signed JSON by fetching the ed25519 keys from the remote server either directly or via a perspective server.
=> Add a KeyRing for storing server keys for verifying signed JSON

federationtypes.go
Returns the events in an order where every event comes after its
auth_events. This is necessary to insert the events into the roomserver
in dendrite.
=> Add method for listing the events in a /state response

.travis.yml, event.go, federationtypes.go, hooks/pre-commit, json.go, keys.go, transaction.go
This seems like a quick way to avoid some common spelling mistakes
=> Add misspell to the precommit hook

event.go
In the message happening on a mismatch between an event's domain and its sender's domain, the wrong variable was used, resulting in meaningless errors such as
```
sender domain doesn't match origin: "matrix.org" != "matrix.org"
```
=> Fix error message on domain mismatch

base64.go, base64_test.go, eventauth.go, eventauth_test.go, eventcontent.go
This PR adds support for `m.room.member` events of `invite` membership derived from `m.room.third_party_invite` events.
=> Support for third-party invites

.travis.yml, client.go, clientevent_test.go, event.go, eventauth.go, eventauth_test.go, eventcrypto.go, eventcrypto_test.go, federationclient.go, federationtypes.go, hooks/pre-commit, keyring.go, keyring_test.go, keys.go, linter.json, request.go, request_test.go, resolve.go, signing.go, stateresolution.go
Inspired by matrix-org/dendrite#210
However:
* It doesn't vendor the linters
* It enables more of the linters
* The linters have been left on their default settings
* Offending code has been annotated with // nolint as required.
=> Use gometalinter

federationclient.go
This PR adds a function to request `PUT /_matrix/federation/v1/invite/{roomID}/{eventID}`.
=> Add function to send an invite over federation

client.go, eventcrypto.go, federationclient.go, federationtypes.go, hooks/pre-commit, keyring.go, keyring_test.go, request.go
This allows us to timeout and cancel requests to matrix servers.
=> Pass a `context.Context` to the federation client methods

event.go, eventcrypto.go, eventcrypto_test.go, federationtypes.go, keyring.go, request.go
It turns out that synapse had a bug for a while (at the end of 2015) where it would send out `join` events which used the event_id (and origin) from the helping server rather than the joining server. We need to accept these events so that we can join rooms which include such events.
=> Handle events where the sender and origin do not match

client.go, federationclient.go
Currently it's unclear what we're waiting for when processing requests which
trigger outbound federation requests. Let's add some logging for them.
=> Log outbound requests

client.go, federationclient.go
"no address found" is not always an appropriate error message. It may also be
useful to log each failing host.
Requires https://github.com/matrix-org/util/pull/14 (so will fail until that lands)
=> Improve the logging of outbound request failures

client.go, federationclient.go
Create Client.DoRequestAndParseResponse, and make Client.DoHTTPRequest public,
to avoid duplication between the two.
=> Factor out common parts of client and federationclient

client.go
Scalar is not currently specifying HTTP timeouts. As mentioned here - https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779 - Go doesn't specify sensible defaults and we need to make sure that we do so, especially in production.
This was specifically brought to light via calls to scalar/api/register, which were timing out and filling up the apache front-end. This endpoint is designed to make outbound HTTP requests to provision a user on a HS. If the the destination HS is poorly configured or not set up for federation, it might fail such that it doesn't timeout.
See - matrix-org/scalar#260 for further details.
=> Set a 30s timeout on client requests.

base64.go, client.go, keyring.go, keyring_test.go, keys.go
This PR reworks the KeyFetcher interface so that, for each key requested, it returns that key in the form of a PublicKeyLookupRequest, rather than the raw JSON which came from the /keys/v1/query response. This will give us a better basis on which to implement fetching keys from
perspectives servers.
The corollary is that we also need to update KeyDatabase to work at the higher level (of keys instead of JSON).
(We'll need to update the application level to handle the changes in interfaces).
=> Make KeyFetcher interface return keys

client.go, keyring.go
... because /key/v2/query is only if you're talking to a perspectives server.
=> Use /key/v2/server to get keys direct

federationclient.go
Construct the Client used by FederationClient correctly, so that it is
configured to time out requests.
=> Fix timeouts for federationclient

eventcrypto.go, eventcrypto_test.go, federationtypes.go
To implement room joins properly, we're going to need to figure out which
events are valid and which are not. A single error isn't going to cut it.
Also add VerifyAllEventSignatures which provides the old behaviour.
=> Make VerifyEventSignatures return a list of errors

client.go
Try to log outbound federation requests more consistently and more usefully
=> Improve logging of outgoing federation requests

appservice.go, clientevent.go, event.go, eventauth_test.go, eventcrypto.go, federationtypes.go, hooks/pre-commit, json.go, redactevent.go, request.go, request_test.go
Typed structs spec'd at: https://matrix.org/docs/spec/application_service/unstable.html#put-transactions-txnid
Also sets RawJSON to be an exported type which was necessary for casting an already JSON-encoded string to a rawJSON.
=> Add application service transaction and event types

eventcontent.go
=> Set state_default to 0 if there isn't a power level event

appservice.go
The spec is out of date on this one. Bug filed [here](https://github.com/matrix-org/matrix-doc/issues/1294).
App Services expect this behavior.
=> Move the age field to an unsigned block

appservice.go
We were using an event type that was specific for AS's, but this is kind of a pain because whenever we add something important to the event type, you'd also have to update this event type so that AS's got the new info as well.
Instead, just use the same type for everything.
=> Remove AS-specific event type in favor of generic Event

edu.go, transaction.go
As used in federation send transaction.
https://matrix.org/docs/spec/server_server/unstable.html#transactions
Also add omitempty to non-essential fields  https://github.com/matrix-org/synapse/blob/3c099219e0506f81fc333ff9d27cc3af5c365a2c/synapse/federation/units.py#L69-L91
`Signed-off-by: Anant Prakash <anantprakashjsr@gmail.com>`
=> Add EDU type used in federation

linter.json
Apparently gometallinter has renamed gas to gosec. alecthomas/gometalinter#505
This fixes travis failure.
`Signed-off-by: Anant Prakash <anantprakashjsr@gmail.com>`
=> Change gas to gosec

.travis.yml, README.md, linter.json
Bumps the minimum golang version to 1.10 due to latest Ubuntu LTS containing 1.10.
=> Update to go v1.10

well_known.go
The go docs says we must call resp.Body.Close().
This frees up resources(sockets)
=> Ensure resp.Body is closed

keyring.go, keys.go
~~Adds parameters to `CheckKeys` that lets you specify whether well-known is being used or not, and the new server name if so.~~
~~https://github.com/matrix-org/matrix-federation-tester/pull/19~~
Simply does some aesthetics updates now as all PR functionality was moved to matrix-federation-tester.
=> Shorten line length of method declaration

eventauth.go
~~We didn't pick up on this because our CI apparently doesn't run `go test`, but this fixes `go test`.~~
This is only caught in golang 1.11 and we're currently on golang 1.10 but with plans to update to 1.11, so might as well get this fixed.
=> Fix type in error

well_known.go
Fixes https://github.com/matrix-org/matrix-federation-tester/issues/44
Show an error if no `m.server` key was found in a .well-known file.
=> Warn on m.server key not found in well-known

federationclient.go
Spec implemented: https://matrix.org/docs/spec/server_server/r0.1.1.html#get-matrix-federation-v1-event-eventid
=> Add support for single event retrieval

client.go, federationclient.go
Make `GetVersion` a client function rather than a federation function.
=> Move GetVersion to client from federation_client

federationclient.go, federationtypes.go
Spec implemented: https://matrix.org/docs/spec/server_server/r0.1.1.html#get-matrix-federation-v1-query-profile
=> Implement profile query API for federation client

filter.go
`event_format` is an optional field: https://matrix.org/docs/spec/client_server/r0.5.0#post-matrix-client-r0-user-userid-filter
=> Validation of filter.EventFormat should allow ""

eventauth.go, eventcontent.go
This also adds a `RoomVersion` field in `createContent`.
=> Support auth check of redaction events in rooms >= v3

tokens/tokens.go, tokens/tokens_handlers.go, tokens/tokens_handlers_test.go
Previously, these tests failed because of an unchecked error, an Errorf call
missing formatting directives, and a token duration value set wrong. They've
gone undetected because the CI runs `go test`, not `go test ./...` and thus
they've not been run.
This PR also refines some docs.
=> Fix failing tests for the tokens package

event.go, eventauth.go, eventauth_test.go, eventcontent.go, eventcrypto.go
Fixes #135.
A few missing fields and JSON tags in some types are also added for uses other than event authentication.
=> Make event content types public

filter.go
I just updated the filter structs to match names and orders of the [r0.5.0](https://matrix.org/docs/spec/client_server/r0.5.0.html#filtering) specs.
=> Updated filters to match r0.5.0 specs

federationtypes.go, federationtypes_test.go
In this PR, i have added the missing `"origin"` field of `RespSendJoin` and also made some changes to `TestRespSendJoinMarshalJSON`.
=> Missing "origin" field added to RespSendJoin

client.go, federationclient.go
This allows passing in a custom `http.Transport`, such as those provided by libp2p, when creating a federation client. Outgoing federation requests will use the custom transport instead of the default TLS senders.
=> Allow creating federation client with custom http.Transport

federationclient.go
This PR does two things:
- Removes the trailing `/` from the backfill URL, which should not be there
- Stops the `roomID` parameter from being encoded twice - `RequestURI()` handles this for us, so this doesn't need to be done twice (or otherwise the escaped value gets escaped again)
=> Fix backfill URL

eventcrypto.go, eventcrypto_test.go
This fixes the event hashing algorithm so that it correctly excludes `signatures` now. It also adds a couple of test from the spec appendies to prove that it works as intended.
=> Fix hashing algorithm

keyring.go
Previously, we would check using the keys from the database, then promptly
discard that and do federation calls.
This patch is required for P2P as the excessive key requests would cause the requesting peer to be temporarily blacklisted on the network.
=> bugfix: don't make federation calls for keys if we don't need to

errors.go, federationtypes.go
We really should return concrete error types for more error conditions but this at least lets me fix the problem where fetching missing auth events over federation in Dendrite.
=> Return MissingAuthEventError when auth events are missing

clientevent.go, event.go, eventversion.go, headeredevent.go, headeredevent_test.go
This PR implements `HeaderedEvent`, which allows bundling additional metadata like room versions along with an event and having the metadata combined/separated correctly when marshalling to/unmarshalling from JSON.
It also includes some new types and room version descriptions which are used by Dendrite.
This is the first of a series of PRs that will implement room versions.
=> Room version metadata and HeaderedEvent

event.go
This does a bit more to ensure `auth_events` and `prev_events` are never `null`, and is a part of the fix in matrix-org/dendrite#951.
=> Try to prevent nil prev_events/auth_events again

eventauth.go, federationclient.go, headeredevent_test.go, invitev2.go, invitev2_test.go, request.go
This PR adds support code for supporting the [`/_matrix/federation/v2/invite`](https://matrix.org/docs/spec/server_server/r0.1.3#put-matrix-federation-v2-invite-roomid-eventid) endpoint.
Maybe it is better to put this stuff into `federationtypes.go` or something, or name it better? Or is it OK as-is?
=> Support code for v2 invites

stateresolutionv2.go
This adds `HeaderedReverseTopologicalOrdering` alongside `ReverseTopologicalOrdering` so that we can use the reverse topological ordering with headered events in Dendrite more cleanly.
=> Add HeaderedReverseTopologicalOrdering

event.go
This fixes a problem where `EventReference`s could get double-base64'd SHA256 hashes in newer event formats.
(Also I'm abandoning my moral distaste for panics right now.)
=> Fix SHA256 generation in new event formats

keyring.go
This spawns goroutines per server for the direct key fetcher and waits for results to return using a wait group. The result is that fetching keys in big rooms now doesn't take forever (a maximum of 30 seconds since that appears to be our outbound timeout) and this reduces the chance that the requestor context expires before we finish:
```
Apr 16 15:41:58 photon-machine docker-compose[3829]: dendrite_monolith | time="2020-04-16T15:41:58.284643563Z" level=info msg="Checking event signatures for 7677 events of room state" func="Check\n\t" file=" [/go/pkg/mod/github.com/matrix-org/gomatrixserverlib@v0.0.0-20200416153646-47a0f63244a5/federationtypes.go:332]" req.id=4sPgj4M4LH8x req.method=POST req.path="/_matrix/client/r0/join/!BAXLHOFjvDKUeLafmO:matrix.org" …
```
=> Parallelise direct key fetcher

eventcrypto.go, eventversion.go, keyring.go, keyring_test.go, request.go, request_test.go
This signature checking so that strict validity checking can be optional (as is needed for room versions 1-4) whilst maintaining it for federation HTTP requests and allowing us to use it for room version 5.
It also fixes some potential panics in tests.
=> Update validity check

federationtypes.go, filter.go
This PR primarily does two things:
- It ensures that the auth and state events are handled properly for `SendRespJoin`, and ensuring that we're checking if the event is allowed against the correct set of auth events.
- It increases `DefaultStateFilter()` to return `math.MaxUint32` limits rather than 20, since this stopped us from ever seeing full room state.
=> SendRespJoin checks

keyring.go
This improves multi-key-fetcher configurations so that we will continue to ask all of the fetchers for keys that we haven't received back.
=> Make sure we're trying next key fetchers if needed

authchain.go, authchain_test.go, backfill.go, backfill_test.go
This currently doesn't make network calls, the next PR will add an implementation of `AuthChainProvider` which will rely entirely on network calls. The intention then is for Dendrite to use that provider as a fallback, after initially trying the database/caches/querying roomserver/magic.
=> Add VerifyEventAuthChain and use it when backfilling

federationtypes.go
This adds a separate `RespInviteV2` struct, since v2 invites don't have the `[200, ...]` response tuple like v1 invites do.
=> Add RespInviteV2

federationclient.go
This uses `RespInviteV2` instead of `RespInvite` for `SendInviteV2`.
=> Fix SendInviteV2 response type

backfill.go, backfill_test.go, load.go, stateresolutionv2.go, stateresolutionv2_test.go
They now both require an `Ordering` which is usually `OrderingAuthEvents`
except in the case of backfilling, where we use `OrderingPrevEvents`.
We need to sort by prev_events for backfilling so we can make optimisations
and not call `/state_ids` repeatedly, as well as work out the state at
that event for snapshots/PDU checks.
=> breaking: Modify the API for ReverseTopologicalOrdering and LoadAndVerify

authstate.go, authstate_test.go, backfill_test.go, load.go
- Step 6 cannot reuse the same code path as it requires the state AFTER the latest room state
- We need the entire `Event` for rolling forward state.
=> Rejig StateProvider API

federationclient.go, federationtypes.go
This adds the necessary intermediate step for unmarshalling the invite v2 response in the correct room version format.
=> Fix v2 invite responses

federationclient.go
Because room version 3 event IDs aren't URL-safe, we need to use query escaping rather than path escaping to stop `+`, `:` and friends from creeping in and mangling the URLs.
=> Use query escaping for event ID fields in URLs

federationclient.go
Reverts #181 and fixes a couple of other places after further investigation and reading the correct RFC this time.
=> Use PathEscape again for path components

keyring.go, keyring_test.go
If `ExpiredTS` is set then we should really return true if the supplied `atTS` is less than the expired time.
=> Fix check on ExpiredTS

filter.go
A subtle bug where the code was returning a constant for unsigned int where it should have been signed. (See L54 of `filter.go` for the type definition.)
=> Use MaxInt32 instead of MaxUint32

federationclient.go
This fixes errors in `SendLeave` and `ExchangeThirdPartyInvite` where a successful but empty response fails because of a `json.Unmarshal(nil)` error.
=> Fix json.Unmarshal(nil) errors

federationclient.go, federationtypes.go, federationtypes_test.go
This fixes both `RespState` so that `state` is now `pdus` in the JSON, and updates `RespSendJoin` so that it no longer uses `RespState`.
=> Fix RespState and RespSendJoin

eventcontent.go
This adds the `is_direct` field to `MemberContent` for DMs.
=> Add IsDirect to MemberContent

stateresolutionv2.go, stateresolutionv2_test.go, stateresolutionv2heaps.go
This updates the state resolution v2 code to primarily juggle pointers around instead of copies of events. Experiments with `pprof` shows that this reduces the allocation footprint of the algorithm by a huge margin.
=> Update state res v2 to work using pointers

stateresolutionv2.go, stateresolutionv2_test.go, stateresolutionv2heaps.go
This is a continuation of #194 to optimise the state res v2 heaps too using pointers instead of copies. Allocator profiling shows an 8x improvement and the heap profiling no longer registers state res v2 as significant.
=> Update state res v2 heaps to use pointers too

keyring.go, keyring_test.go
For the server key API component, it will make life a lot easier if we can continue to use `PublicKeyLookupRequest` as a map key, but we need to implement `encoding.TextMarshaler` and `encoding.TextUnmarshaler` so that `encoding/json` can encode and decode the map keys as valid JSON.
=> Allow marshalling and unmarshalling PublicKeyLookupRequest to/from text

event.go, event_test.go, headeredevent.go
This should hopefully help us to avoid bugs like matrix-org/dendrite#1070.
=> Prevent NewEventFromUntrustedJSON from accepting headered events

eventversion.go, hooks/pre-commit, stateresolution.go
Since gomatrixserverlib ultimately implements all of the logic related to specific room versions, it makes sense that it should also own the information about which versions are supported/stable.
=> Responsibility for marking room versions supported/stable

json.go, json_test.go
This checks for apparently-forbidden float values when enforcing canonical JSON in room version 6.
=> Check for JSON floats when enforcing canonical JSON

keyring.go, keyring_test.go
When we retrieve a key from the database (or cache), then check the validity of the key. If we've passed the validity but the key is not yet expired, re-request it from the server to get the updated validity (or replacement keys).
=> Re-request keys that have passed their validity lifetime

authchain.go, authstate.go, federationtypes.go
This uses `AuthChainProvider` as an optional parameter to:
- `RespState.Check()`
- `RespSendJoin.Check()`
- `checkAllowedByAuthEvents()`
The idea here is that the above functions don't just give up entirely if they hit a missing auth event, but instead can delegate to the provided function to *attempt* to retrieve the missing event. This means that we don't have to return to the caller and repeat the entire set of checks for each missing auth event.
If an `AuthChainProvider` isn't supplied then a `MissingAuthEventError` will be returned as usual.
=> Use AuthChainProvider for Check etc

keyring.go
This will:
- increase logging a bit when things go wrong fetching keys
- not re-request keys that are expired
- still allow updates that are past the validity to be returned, as `checkUsingKeys` will yell if there's a problem with them
=> Adjust DirectKeyFetcher

keyring.go
This restricts direct key fetch requests to 15 seconds, otherwise the worker pool of 64 direct fetchers can be saturated for a long time by fetch requests which are failing due to TCP timeouts or such.
=> 15 second timeout on direct key fetch requests

federationtypes.go
This PR modifies the `RespState` checks so that we:
- Don't try to verify against events with failed signatures
- Remove events that failed signature checks from the `RespState` auth/state events, so that they don't get processed downstream 
This seems to make it possible to join HQ again.
=> Handle failed signature checks in RespState better

client.go
This PR reduces the `Outgoing request`/`Outgoing request returned` logging to trace level.
Associated with matrix-org/dendrite#1244.
=> Request logging to trace level

client.go, federationclient.go, federationclient_test.go
This makes skipping certificate validation optional so that we can sort matrix-org/dendrite#760.
=> Allow enforcing X.509 certificate validity (MSC1711)

authstate.go, backfill.go, backfill_test.go
This adds two new interfaces to allow us to use the federation sender API as the client for backfill and federated state.
It also fixes two disparate definitions for `Backfill`.
=> BackfillClient, FederatedStateClient

eventauth.go
needed for peeking (even though it's not technically a membership state, we use it in dendrite as the key for the appropriate sync section for [MSC2753](https://github.com/matrix-org/matrix-doc/pull/2753) style peeking)
=> add peek constant

federationtypes.go
This happened because we were trimming things out of the slices but the original `range` was running on a copy of the slice, meaning that we'd hit an invalid index and panic.
This helps matrix-org/dendrite#1401 — sort of. Joining that room still doesn't work because of a bad state event in the room, but at least we don't panic anymore.
=> Don't cause panics when trimming failed auth/state events

federationtypes.go
This means that we can join rooms that have invalid state events by simply ignoring them, so long as the event isn't critical to the join in some other way (e.g. as an auth event).
=> Ignore events with invalid signatures in RespState/RespSendJoin

keys.go
Construct breaks if it's null instead of an array. It's a legacy field which shouldn't be used anyway, so it could be removed altogether, but this is just a quick fix that shouldn't affect anything else.
Signed-off-by: Tulir Asokan &lt;tulir@maunium.net&gt;
=> Omit tls_fingerprints from server keys when empty

request.go
This fixes the `readHTTPRequest` function so that it handles MIME in the `Content-Type` header properly. The old check would match `application/json` but would fail on `application/json; charset=utf-8`.
=> Handle Content-Type header properly

eventauth.go, eventcontent.go
This ensures that if an event contains an invalid display name or avatar URL type (e.g. not a `string`), we'll still accept the event as long as the `membership` key is fine.
=> Don't fail on invalid display names/avatar URL formats

stateresolutionv2.go
This fixes a bug in reverse topological ordering where we'd incorrectly give up processing inbound references after the first prev/auth event.
=> Fix bug in reverse topological ordering

client.go, federationclient.go, federationclient_test.go
This shuffles the client creation functions a bit so we can create things with/without transports and with/without timeouts.
=> Update client functions

stateresolutionv2.go, stateresolutionv2_test.go
This makes a number of optimisations in the state res v2 code, largely around preallocating backing arrays, identifying unconflicted events using a map rather than loops, hitting some common event functions less often.
=> State res v2 optimisations

request.go
https://matrix.org/docs/spec/server_server/r0.1.4#api-standards
> all strings MUST be encoded as UTF-8.
=> reject invalid UTF-8 for FederationRequest

event.go
This adds `NewEventFromTrustedJSONWithEventID`, which is used specifically when we're pulling the event out of storage and *we already know the event ID*. This saves us *a lot* of CPU time because then we don't need to calculate the reference hash, redact, canonicalise etc just to work it out.
=> Add NewEventFromTrustedJSONWithEventID

client.go, federationclient.go, federationclient_test.go
This removes some of the duplicate messy functions and returns us to just having `NewClient` and `NewFederationClient`. You can provide one or more `ClientOpts` to control the transport, timeout, TLS validation, DNS cache etc.
=> Simplify NewClient and NewFederationClient with ClientOpts

stateresolution.go
Handling multiple of the same event might be causing us to use more memory than we need to during state resolution.
=> Deduplicate events in ResolveConflicts input

federationtypes.go
Add the `omitempty` annotation to `MSC2946SpacesRequest.ExcludeRooms` and `MSC2946SpacesRequest.MaxRoomsPerSpace` as MSC2946 states these are optional parameters (and keeping them around with their zero value might lead to type errors when interacting with other homeservers). See https://github.com/matrix-org/synapse/issues/10056 for more context.
=> Make optional params from MSC2946 actually optional

event.go, event_test.go
We should be sure that user IDs match https://matrix.org/docs/spec/appendices#id12
=> Ensure user IDs match the spec

.travis.yml
TravisCI builds are failing to start, and as of https://github.com/matrix-org/pipelines/pull/125 we have the same steps running on Buildkite already. So there's not much point in keeping TravisCI around.
Signed-off-by: `Andrew Morgan <andrewm@element.io>`
=> Remove TravisCI

eventcontent.go, eventcontent_test.go
The existence of this type is due to a long-standing Synapse bug where power levels can be strings (matrix-org/synapse#1237, matrix-org/matrix-doc#3264). However, it gets hit quite hard when resolving room state as we need to pull power levels out of possibly a large set of events.
This PR changes from `json.Unmarshal` to `strconv.ParseInt`/`strconv.ParseFloat` where possible, as they are significantly faster (not relying on `reflect` internally, for a start).
Before this PR:
```
BenchmarkLevelJSONValueInt-12             741554              1430 ns/op
BenchmarkLevelJSONValueFloat-12           317689              3312 ns/op
BenchmarkLevelJSONValueString-12          547220              2123 ns/op
```
With this PR:
```
BenchmarkLevelJSONValueInt-12            1332276               884.9 …
```
=> Optimise levelJSONValue

eventcontent.go
This is to address a few sytests, notably `Remote servers cannot set power levels in rooms without existing powerlevels` which checks that if a room has no PL event then a random user can't then set the PLs, it has to be the creator.
This change fixes the issue as if there is no PL event then the room creator gets a PL of 100, and everyone else is 0. Making the state_default 50 then means randoms cannot set the PL. See comments for relevant synapse code.
=> state_default is 50 not 0

eventauth.go, stateresolutionv2.go, stateresolutionv2_test.go
This improves state resolution v2 performance quite dramatically in large rooms when authing and applying events by reducing the number of times that we parse the content of the create, power levels and join rule events from the auth event provider.
=> Improve state resolution v2 performance using allowerContext

federationclient.go
This should fix matrix-org/dendrite#1927.
=> Use intermediate step for RespSendJoin to drop invalid events

eventauth.go, eventversion.go
This PR implements knocking as per room version 7. This should probably have been done in #263?
Spec reference summarising the changes: https://spec.matrix.org/unstable/rooms/v7/
```
For checks perfomed upon m.room.member events, the following conditions are added in context:
If type is `m.room.member`:
...
* If `membership` is `ban`:
...
* If `membership` is `knock`:
i. If the `join_rule` is anything other than `knock`, reject.
ii. If `sender` does not match `state_key`, reject.
iii. If the `sender`'s current membership is not `ban`, `invite`, or `join`, allow.
iv. Otherwise, reject.
...
```
=> Knocking for Room Version 7

event.go, invitev2.go
This should make matrix-org/dendrite#1930 much simpler because then we can just try to type-cast the error to `gomatrixserverlib.UnsupportedRoomVersionError`.
It also adds the check to the various `NewEvent` functions for good measure.
=> Return concrete error type for unsupported room version 

base64.go, base64_test.go, crosssigning.go, federationtypes.go
This includes some types for cross-signing, as well as the ability to marshal unmarshal `Base64Bytes` to/from a database.
=> Cross-signing types, `Base64Types` updates

event.go, eventcrypto.go, signing.go
This PR refactors `SignJSON` to just be so much less of a mess by using `gjson`/`sjson` instead, and also ensures that old signatures are preserved when we unmarshal an event into an `EventBuilder`.
=> Refactor `SignJSON`, preserve signatures in `EventBuilder`

federationclient.go, federationtypes.go
Else it doesn't deserialise events. Required for complement tests.
=> Add custom unmarshaller for /event_auth

event.go, eventcontent.go, eventcontent_test.go, eventversion.go
This is an implementation of matrix-org/matrix-doc#3667 to enforce that power levels are integers rather than accepting stringified equivalents. 
It works by adding a new proof-of-concept `org.matrix.msc3667` room version based on room version 7. Unmarshalling stringified power levels with this room version should fail outright.
=> MSC3667 implementation

client.go, resolve.go, resolve_test.go, well_known.go
This stops them from potentially wedging for aaaaages.
=> Use contexts for well-known and DNS SRV lookups

eventcontent.go, eventcontent_test.go
Python's [`int()`](https://docs.python.org/3/library/functions.html#int) function is ✨ s p e c i a l ✨ and means that string power levels can be padded with whitespace. We now trim this whitespace, which at least fixes joining Watercooler.
=> Trim whitespace from string power levels

authstate.go, federationclient.go, federationclient_test.go, federationtypes.go, federationtypes_test.go, json.go, json_test.go
This is largely driven by the desire to use GMSL Response types without knowing the room version up front. Now basically every response just returns these new types which then have functions to deserialise them into events with the given room version.
=> Add EventJSON and EventJSONs types

client.go
Should make the [proxy_outbound](https://github.com/matrix-org/dendrite/blob/5106cc807cf22a95420b24f6bfdd5c9ac8aa06de/dendrite-config.yaml#L207-L212) config obsolete, since it uses the default mechanism to get the proxy settings.
=> Use http.DefaultTransport, which loads proxy config from environment

federationclient.go, federationtypes.go, federationtypes_test.go, go.mod
[MSC3706](https://github.com/matrix-org/matrix-doc/pull/3706) adds some new fields to `/send_join` responses. Here we add support for the new fields, and the new query param
=> Add support for partial state in `send_join` responses

stateresolutionv2.go
Reduces new allocations in `createPowerLevelMainline`, `kahnsAlgorithmUsingAuthEvents` and `kahnsAlgorithmUsingPrevEvents` that would happen when prepending to the graph.
=> Reduce allocations in state resolution v2

request.go, request_test.go
This sets the `destination=` field in the federation request auth header so that a proxy can distinguish the target of a federation request without needing to rely on the `Host` header, which is more likely to be set to the hostname of the proxy itself. This should be useful for P2P.
=> Implement `destination` field in `X-Matrix` header as per MSC3383

client.go
This PR makes the following changes:
* If HTTP/2 is possible, we should use it — that way we can multiplex multiple in-flight HTTP requests onto the same HTTP/2 connection rather than having to open multiple connections
* If connection keepalives are enabled, limit to 1 idle request and set the timeout to 5 minutes
* If connection keepalives are disabled:
* If HTTP/1 is in use, it will be closed as soon as the request completes
* If HTTP/2 is in use, it will be closed "as soon as possible" (see golang/net#48)
* Reap unused federation tripper entries for remote hosts after 5 minutes, otherwise we'll just hold onto these things in memory indefinitely even if we stop talking to a given host
* Use a TLS client session cache, which should allow TLS resumption in some cases, potentially saving …
=> `Client` and federation tripper improvements

event.go, stateresolutionv2_test.go
This removes `EventID` from `eventFormatV2Fields` and puts a central `eventID` field in the `Event` struct which will either be populated from the `eventFormatV1Fields` (room versions 1-2) or from computing our own event ID (room versions 3 and later).
Beforehand we were trying to find and remove the `event_id` field on every event in room version 3 and later, even though it probably isn't present. The `sjson` call had a few allocations even though it was not really accomplishing anything.
Even if the `event_id` field is present in those room versions, which it really shouldn't be, removing it would break the event signatures, when instead we should just be ignoring what the event ID is and computing our own.
=> Remove `event_id` field from `eventFormatV2Fields`

eventcontent.go
This fixes cases where `power_level_content_override` in `/createRoom` can't set levels higher than 100. It only takes effect if there's no power level event already.
=> When no power level is available, give the creator user ID the maximum possible power level

event.go, federationtypes.go, go.mod, go.sum
This PR makes the following changes:
* `RespState.Check()` will now return the unmarshalled events as well as modifying the `RespState` JSONs — we go through the effort of unmarshalling so we'd might as well — this will remove an unnecessary marshalling round-trip step when processing `RespSendJoin`;
* Untrusted events now strip the `"unsigned"` key.
=> `RespState` and untrusted event tweaks

filter.go, filter_test.go
This should allow Dendrite to parse filters like ` { "room": "state": { "types": [] } }` correctly.
=> Make it possible to correctly parse filters

client.go, federationclient.go
That way we can use `Client` to do regular requests without performing well-known or SRV lookups.
=> Control whether `Client` performs well-known or SRV lookups, update `FederationClient`

eventauth.go, eventauth_test.go
The `checkUserLevels` function was considering the default user level if the user didn't have a key defined, which meant that promoting or demoting a user above/below the default power levels could result in the event auth failing, even though the changes should be allowed.
It could also end up adding duplicates, which just seems wasteful.
=> Fix bugs in `checkUserLevels`

base64.go, base64_test.go
This should fix the issue encountered in https://github.com/matrix-org/dendrite/commit/8ae34c4e5f78584f0edb479f5a893556d2b95d19
=> Fix `Base64Bytes` sql.Scanner

stateresolutionv2.go, stateresolutionv2_test.go
This PR should fix some state res bugs by not allowing an event directly related to a power event from the conflicted set from being reapplied later as a non-power event.
=> Pull in related events into the conflicted control events

device_update.go
This should address the cause of matrix-org/synapse#12829. These fields are optional, so we should omit them if they are empty instead of sending `null`.
=> Specify `omitempty` for some fields in `DeviceListUpdateEvent`

eventauth.go
Previously we had an `if` statement for each join rule, which is excessive because an invited user is always allowed to join. This PR simplifies it so that it's just a single statement and that way it also covers the `"restricted"` join rule.
=> Tweak event auth to always allow an invited user to join

json.go, json_test.go
The Matrix specification says everything should be UTF-8:
> For the default HTTP transport, all API calls use a Content-Type of application/json. In addition, all strings MUST be encoded as UTF-8.
... and our handling of UTF-16 surrogates was quite broken here, which sometimes resulted in broken JSON after `CompactJSON`.
=> Remove broken surrogate handling for UTF-16

eventversion.go
This PR defines a room version `"10"`, containing both #310 and #284, as per [MSC3604](https://github.com/matrix-org/matrix-spec-proposals/pull/3604).
=> Add room version 10 support

stateresolutionv2.go
Otherwise the partial state isn't correctly populated for authing and applying later conflicted events.
=> Auth and apply auth chain

eventcontent.go, eventcontent_test.go, headeredevent.go
Updates the default value to `shared` as per the spec:
> By default if no history_visibility is set, or if the value is not understood, the visibility is assumed to be shared.
Adds some helper functions to convert between int and string (e.g. when storing numeric values in the database)
=> History visibility convenience functions

backfill.go, load.go
With this we should be able to skip over different errors from `LoadAndVerify` (used when backfilling in Dendrite) or rather ignore the error and still persist the event.
The event is not sent to the output stream nor is it rejected in Dendrite.
Tested on my instance and I was able to scroll back in "Dendrite alerts" until the beginning of the room.
=> Always add the event in LoadAndVerify, even in case of an error

event.go, event_test.go, eventcrypto.go, eventcrypto_test.go, redactevent.go, redactevent_test.go
This makes two changes:
1. `(*Event).Redact()` now doesn't return a copy of the event, but instead modifies the event from the receiver, since all we ever seem to do is `event = event.Redact()`;
2. Exports `RedactEventJSON` so that it can be used in combination with `VerifyJSON` without having to round-trip an `*Event`
=> Redaction tweaks

client.go
Client-server spec 1.1, 1.2, and 1.3 use /v3/ for media downloads
https://spec.matrix.org/v1.3/client-server-api/#get_matrixmediav3downloadservernamemediaid
so let's use this one.
fixes #323
Signed-off-by: Sebastian Spaeth <Sebastian@SSpaeth.de>
=> client.go: Use /v3/ for media downloads

event.go, eventcontent.go, eventcontent_test.go
As mentioned in https://github.com/matrix-org/dendrite/pull/2533#discussion_r921056138, implements `sql.Scanner` & `sql.Valuer`
=> Implement sql.Scanner & sql.Valuer for HistoryVisibilty

stateresolutionv2.go
This preserves the history visibility when using `HeaderedReverseTopologicalOrdering`, otherwise incremental syncs in Dendrite can't check the visibility of an event.
=> Preserve history visibility in `HeaderedReverseTopologicalOrdering`

federationclient.go
Sorry about this. Turns out that /send_knock doesn't have a v2, but the format looks the same as /send_join's v2...
Follow-up to #329. I have since figured how to use gomatrixserverlib locally as an override in Complement and have tested it this time :-)
=> Fix /send_knock to be v1

json.go, json_test.go
This somewhat reverts #314 and refactors things so that the broken JSON that could happen before with faulty surrogates will no longer happen.
=> UTF-16 surrogate handling (again)

eventauth.go
Required by the auth rules:
```
1. If type is m.room.create:
...
4. If content has no creator field, reject.
```
=> Check for existence of `"creator"` field in `m.room.create`

eventauth.go
`Users` map access would return 0 for users with no explicit power level, even though it should default to `users_default`. The existing `UserLevel()` helper method already handles it correctly, so this simply switches power level event auth to using that method.
=> Fix authorizing PL changes when users_default≠0

event.go, eventcrypto.go, eventcrypto_test.go
This nukes the `origin` field from PDUs as per matrix-org/matrix-spec#998.
=> Remove `origin` field from PDUs

federationtypes.go
This should fix cases where Synapse users can upload absolute nonsense into their device keys and then that causes the entire devices response to fail to unmarshal.
This has happened both in the `"devices"` and `"stream_id"` keys that I can see.
=> `RespUserDevices` intermediate decoding

event.go
This effectively reverts the change made in [5f66df0](https://github.com/matrix-org/gomatrixserverlib/commit/5f66df0) to bytes instead of codepoints, since Synapse will now enforce the same after matrix-org/synapse#13710. 
History here is that Synapse originally calculated bytes in Python 2.x, started counting codepoints in Python 3.x pretty much by accident and then the spec was ambiguous after the fact (hence matrix-org/matrix-spec#1001).
Rationale is that bytes are probably easier for implementations to manage and less likely to generate huge indexes for client-side databases (especially where limits might exist like LMDB). 
cc @reivilibre
=> Enforce `type`, `sender`, `state_key` and `room_id` lengths using bytes rather than codepoints

transaction.go
We're currently marshalling JSON fields which are not in the spec. They are kept on the struct, as they are used in other places.
https://spec.matrix.org/v1.4/server-server-api/#put_matrixfederationv1sendtxnid
=> Remove unspecced fields from `Transaction`

backfill.go, backfill_test.go
As otherwise we silently drop the error to the ground.
=> Let `RequestBackfill` return an error

federationclient.go, federationtypes.go, federationtypes_test.go
I haven't made any effort to maintain backwards compatibility (unlike in https://github.com/matrix-org/synapse/pull/14832). I'm happy to do so if needed, but might need some guidance.
Synapse issue: https://github.com/matrix-org/synapse/issues/14828
Synapse PR: https://github.com/matrix-org/synapse/pull/14832
Complement PR: https://github.com/matrix-org/complement/pull/583
GMSL PR: https://github.com/matrix-org/gomatrixserverlib/pull/350
MSC: https://github.com/matrix-org/matrix-spec-proposals/pull/3706
Spec diff: https://github.com/matrix-org/matrix-spec/pull/1393
Signed-off-by: `David Robertson <davidr@element.io>`
=> Use stable identifiers from MSC3706 (Faster joins)

authchain.go, authstate.go, fclient/client.go, fclient/crosssigning.go, fclient/dnscache.go, fclient/dnscache_test.go, fclient/federationclient.go, fclient/federationclient_test.go, fclient/federationtypes.go, fclient/federationtypes_test.go, fclient/relaytypes.go, fclient/resolve.go, fclient/resolve_test.go, fclient/well_known.go, servername.go
This removes around 3k out of 16k LoC to a separate package which (mostly) is boring type structs and HTTP wrapper functions.
A notable exception is `RespSendJoin.Check` and `RespState.Check` which do complex logic which suprise surprise isn't tested yet.
This will be refactored further in another PR.
=> refactor: move fedclient stuff to a new `fclient` package

event.go, event_test.go
Adds a function that:
- gets the necessary state for an event
- populates the auth_events field
- builds the event
These are all already provided by GMSL so this is just a higher level combination of functionality.
=> Move common Dendrite event building use case into GMSL

event.go, event_builder.go, eventauth.go, eventcrypto.go, handlejoin.go, handleleave.go, join.go, pdu.go, spec/base64.go, stateresolutionv2_test.go
Also removes `CacheCost` which is now implemented in Dendrite.
=> Remove methods returning/using `EventReference`

fclient/federationtypes.go, fclient/invitev2.go, fclient/invitev2_test.go, handleinvite.go, handleinvite_test.go, handlejoin_test.go, invite.go, performinvite.go, performinvite_test.go, performjoin.go, performjoin_test.go
Pulls over both outbound & inbound invite logic from Dendrite.
=> Move Invite logic to GMSL

performjoin.go, performjoin_test.go, spec/senderid.go
Don't pass in senderID to PerformJoin since we don't know what the senderID is yet.
We require the room version from the response to make_join before we will know how to correctly assign the senderID.
=> Remove senderID input from PerformJoin

eventcontent.go, spec/eventtypes.go, spec/roomtypes.go
Add some constants used in space summaries / room hierarchy ( https://github.com/matrix-org/dendrite/pull/3134 )
Signed-off-by: `Sam Wedgwood <sam@wedgwood.dev>`
=> Add constants used in space summaries

eventversion.go
Self-explanatory
Signed-off-by: `Sam Wedgwood <sam@wedgwood.dev>`
=> add function to check if room version is marked as stable

spec/senderid.go, spec/senderid_test.go, spec/userid.go
Including some tests for sender IDs
Signed-off-by: `Sam Wedgwood <sam@wedgwood.dev>`
=> Add more methods for converting to/from sender IDs

.golangci.yml, stateresolutionv2.go, stateresolutionv2_test.go
The spec says:
> **Iterative auth checks.** The iterative auth checks algorithm takes as input an initial room state and a sorted list of state events, and constructs a new room state by iterating through the event list and applying the state event to the room state if the state event is allowed by the [authorization rules](https://spec.matrix.org/v1.8/server-server-api#authorization-rules). If the state event is not allowed by the authorization rules, then the event is ignored. If a `(event_type, state_key)` key that is required for checking the authorization rules is not present in the state, then the appropriate state event from the event’s `auth_events` is used if the auth event is not rejected.
The part we didn't do, given the membership event may not be resolved (e.g. it is …
=> Fix possible state reset issue

stateresolution.go, stateresolution_test.go, stateresolutionv2.go, stateresolutionv2_test.go
To be even more spec compliant, this adds a `IsRejected` type/function when resolving state.
(Part 2 of https://github.com/matrix-org/gomatrixserverlib/pull/419)
=> Check if event is rejected before using it for auth

keyring.go
To avoid confusion about e.g. being unable to fetch keys from matrix.org.
=> Avoid logging issues if we still could fetch keys

json.go, json_test.go
This aligns with the behaviour exhibited by Ruma & Synapse's canonicaljson
=> Convert unicode escapse to lowercase

fclient/federationtypes.go
Part of https://github.com/matrix-org/dendrite/issues/3218
=> Remove `aliases` from `PublicRoom` as per MSC2432

eventauth.go, eventauth_test.go
Knocking is not allowed in `restricted` rooms.
=> Fix event auth for knocking

fclient/request.go, fclient/request_test.go
=> Trim whitespace in X-Matrix header

.github/workflows/tests.yml, .golangci.yml, fclient/client.go, fclient/federationclient_test.go, fclient/request.go, spec/matrixerror.go, tokens/tokens_test.go
A bunch of changes to get the linter (and CI in general) passing again.
Review commit-by-commit for details of the changes.
=> Update linter config

fclient/well_known.go
Fix a bug in `LookupWellKnown` which would cause it only to read part of the HTTP response body if it spanned multiple TCP segments.
Fixes: https://github.com/matrix-org/gomatrixserverlib/issues/440
=> Fix `LookupWellKnown` to read full response

.github/workflows/tests.yml, README.md, authstate.go, backfill.go, eventV1.go, eventauth.go, eventauth_test.go, go.mod, handleinvite_test.go, handlejoin.go, handlejoin_test.go, handleleave.go, json.go, performinvite.go, performjoin_test.go, stateresolutionv2.go, stateresolutionv2_test.go, stateresolutionv2heaps.go
This contains various backports from Harmony:
* Reduced allocations and performance improvements in state resolution
* Reduced allocations and performance improvements in JSON handling
* Event auth fixes, including correct error surfacing
* Correct event ordering when returning from `PerformBackfill` calls
* Improved handling rejected events in state resolution applies
Closes #439 as superseded by changes in this PR.
Signed-off-by: Neil Alexander <git@neilalexander.dev>
=> Performance and bug-fix backports

.github/workflows/tests.yml, fclient/crosssigning.go, fclient/crosssigning_test.go
Playing around with Copilot, code is mostly generated (but reviewed)
Also fixes CI by using the correct repository for Dendrite.
=> Add Equal method for CrossSigningKey

spec/timestamp.go
It is a bit safer to convert `time.Time` using a standard `t.UnixMilli()` method rather than `t.UnixNano() / 1000000`
Signed-off-by: `Roman Isaev <mdnight@riseup.net>`
=> Minor improvement of spec.AsTimestamp

spec/matrixerror.go
This pull request includes a small change to the `spec/matrixerror.go` file. The change adds a new error code `ErrorUnknownPos` to the `MatrixErrorCode` type. This error is used by the simplified sliding sync 
* [`spec/matrixerror.go`](diffhunk://#diff-3fd6b2645e9d58a86473fb344ae5b3d849c3085399bf76809aa854e54b6a73f3R26): Added `ErrorUnknownPos` to the `MatrixErrorCode` type.
https://github.com/matrix-org/matrix-spec-proposals/blob/erikj/sss/proposals/4186-simplified-sliding-sync.md#connections
Signed-off-by: `Roman Isaev <mdnight@riseup.net>`
=> add M_UNKNOWN_POS to error constants

fclient/federationclient.go, fclient/federationclient_test.go
Discovered while checking Grafana and wondering why there was one server being hit over and over again.
Turns out that we were sending 
```json
{
"device_keys": {
"@alice:example.com": null
}
}
```
instead of an empty list.
This should fix it, even though the server in question still seems to return an invalid response.
=> Fix an issue where we would send an invalid `/user/keys/query` request

stateresolutionv2.go
Signed-off-by: `Your Name <your@email.example.org>`
=> Horrible fix for https://github.com/element-hq/dendrite/issues/3629
