matrix-org/gomatrixserverlib

- keys.go
and for checking that the response is valid
> Functions for fetching keys from a server 

- client.go
- signing_test.go
Manually tested with my open openid token and it works on matrix.org.
> Add Client type

- event.go
- eventauth.go
- eventauth_test.go
- eventcontent.go
- eventcontent_test.go
Modify eventauth to use gomatrixserverlib's Event type
> Move eventauth into gomatrixserverlib

- eventauth.go
- eventauth_test.go
- eventcontent.go
> s/AuthEvents/AuthEventProvider/g and add map-based impl

- clientevent.go
- clientevent_test.go
- event.go
This is required for the sync server as per https://github.com/matrix-org/dendrite/pull/69
> Add ClientEvent and more Event functions

- signing.go
> Add comments to explain more of SignJSON and VerifyJSON

- event.go
- event_examples_test.go
I was getting annoyed by all the "TODO: this should be in gomatrixserverlib" markers in dendrite.
> Add some utility methods to Event that are useful in dendrite

- event.go
- federationclient.go
Function for 3PID invite exchange over federation + bugfix.
> 3PID invite exchange over federation

- federationtypes.go
Don't swallow the error when verification fails
> Respect result from VerifyEventSignatures

- hooks/pre-commit
(rather than what's in our WC)
> run commit hook on what we're committing

- keyring.go
- keyring_test.go
... and then use it in some logging
> Add FetcherName() method to KeyFetcher

- .travis.yml
- travis.sh
... so that it can be run locally if desired
(and set -u on the go get)
> Factor travis stuff out to a script

- client.go
- keyring.go
- keyring_test.go
... for consistency with PublicKeyLookupResult, because I keep failing at
auto-complete.
> Rename PublicKeyRequest to PublicKeyLookupRequest

- tokens/tokens.go
- tokens/tokens_handlers.go
- tokens/tokens_handlers_test.go
- tokens/tokens_test.go
- travis.sh
From
[dendrite#437](https://github.com/matrix-org/dendrite/pull/437)
[dendrite#447](https://github.com/matrix-org/dendrite/pull/447)
`Signed-off-by: Anant Prakash <anantprakashjsr@gmail.com>`
> Add tokens library

- filter.go
Added the structs & functions related to filtering, taken from gomatrix lib.
See https://github.com/matrix-org/dendrite/pull/436#discussion_r192050404
Note: there is a copyright header for Jan Christian Grünhage
> Added filter structs

- eventauth.go
`Signed-off-by: Anant Prakash <anantprakashjsr@gmail.com>`
> Add const for m.typing

- keyring.go
- keys.go
Fixes https://github.com/matrix-org/matrix-federation-tester/issues/18
Paired with https://github.com/matrix-org/matrix-federation-tester/pull/25
> Remove TLSFingerprint checks

- federationtypes.go
- federationtypes_test.go
Fixes a bug where hostnames starting with digits were rejected
> Fix hostname validation bug

- client.go
- go.mod
- go.sum
- resolve.go
- resolve_test.go
- well_known.go
> Add support for .well-known when resolving a server name

- federationclient.go
- version.go
Adds a simple function to the federation client for getting the reported server version.
> Add federation client function for getting server version

- keys.go
Fixes https://github.com/matrix-org/matrix-federation-tester/issues/41 and https://github.com/matrix-org/matrix-federation-tester/issues/40
> Make FetchKeysDirect generate nicer human-readable messages so they display on the federation tester in a nicer way

- federationtypes.go
> Check if a server name isn't empty before trying to validate it

- federationclient.go
- federationtypes.go
Spec implemented: https://matrix.org/docs/spec/server_server/r0.1.1.html#get-matrix-federation-v1-publicrooms
> Implement publicRooms API for federation client

- clientevent.go
> Support "redacts" key in client events

- eventauth.go
- eventcontent.go
- eventcrypto.go
> Make constants in eventauth.go public

- hooks/pre-commit
Note that this PR is based on the branch of #137 so the changes in that PR can be tested by the CI. Once the CI build for this PR passes, #137 should be good to merge. I'll rebase this PR branch onto master after #137 is done.
> Run go test for ./..., not just the current directory

- resolve_test.go
Travis CI builds have failed toooooo many times.
> Use a random available port for the mock DNS server in tests

- resolve_test.go
Broadly I meant to mention those points in #141 but missed it before it was merged because the PR got lost in notifs. Sorry about that.
* Rename `listenAddr` into `udpAddr` and `actualListenAddr` into `listenAddr` because the naming doesn't make sense unless you read the whole code of the function (i.e. it hasn't been spontaneously clear to me how `actualListenAddr` differed from `listenAddr`).
* Gave the comments more details about what's happening and why we do things like this.
* Used `Errorf` instead of `Sprintf` in `panic`s because afaik giving `panic` errors is more idiomatic of Go.
Feel free to complain if one of my points sound unfair/wrong, I'm happy to revert if needed.
> Variables naming and comments faff on setting up test DNS server

- clientevent.go
- event.go
- eventversion.go
This defines the core characteristics of each room version, and the exported types that Dendrite will use to implement them.
> Define room version characteristics and types

- federationclient.go
- federationtypes.go
This adds `MissingEvents`, `RespMissingEvents` and `LookupMissingEvents()`.
> LookupMissingEvents

- authstate.go
- authstate_test.go
- backfill.go
- backfill_test.go
- load.go
Technically it will also do step 6 but that needs the current forward extremity event ID.
> Implement step 5 of PDU checks for backfilling

- keyring.go
- keyring_test.go
This updates the strict key validity rules so that they match the [spec for v5 rooms](https://matrix.org/docs/spec/rooms/v5#signing-key-validity-period).
> Update strict validity for v5 rules

- event.go
- event_test.go
- eventcontent.go
Also fixes a bug in `Membership()` which would incorrectly return a value if there was no state key.
> Add more helper functions to Event

- federationtypes.go
This adds:
- `RespUserDevices`
- `RespUserDevice`
- `RespUserDeviceKeys`
> Add structs for /_matrix/federation/v1/user/devices/{userId}

- errors.go
- event.go
- eventauth.go
- eventcontent.go
- eventcrypto.go
- eventcrypto_test.go
- eventversion.go
- json.go
- json_test.go
- redactevent.go
This implements the functionality required for room version 6 support. I'm not particularly thrilled about the reflection to verify the JSON int bounds but at this stage I'm not sure how better to handle it.
> Room version 6 support

- federationclient.go
Should make some sytests pass!
> Fallback to v1 send_leave if v2 404s

- federationtypes.go
This PR allows gomatrixserverlib to just *ignore* invalid auth events, on the basis that if we omit anything that's important, we will still fail to auth the event anyway.
This means that broken signatures and extraneous auth event references (shout-out to Conduit!) shouldn't kill room joins.
> Ignore broken state/auth events in RespState/RespSendJoin

- eventauth.go
To be used in dendrite. (https://github.com/matrix-org/dendrite/pull/1528)
> Add MReceipt const

- clientevent.go
Makes some more fields omit empty, required for cleaner receipt EDUs
> Make more fields omitempty in ClientEvent

- json.go
In preparation for another PR on Dendrite
> Make canonical json error public

- appservice.go
- authchain.go
- authchain_test.go
- authstate.go
- authstate_test.go
- backfill.go
- backfill_test.go
- clientevent.go
- event.go
- eventauth.go
- eventauth_test.go
- eventcontent.go
- eventcrypto.go
- eventcrypto_test.go
- federationclient.go
- federationclient_test.go
- federationtypes.go
- headeredevent.go
- headeredevent_test.go
- invitev2.go
- invitev2_test.go
- load.go
- stateresolution.go
- stateresolution_test.go
- stateresolutionv2.go
- stateresolutionv2_test.go
> Pass pointers to events — reloaded

- headeredevent.go
> Add UnmarshalJSONWithEventID to HeaderedEvent

- client.go
This caches the well-known/DNS SRV'd addresses so that we don't hit them every time we make a federation request.
If the federation round-tripper fails to connect to all of the cached nodes then we'll clear the entries from the cache and try a network lookup again.
This should fix #246.
> Cache resolved server addresses

- federationclient.go
- federationtypes.go
> MSC2946: Update to use stripped state

- well_known.go
This prevents us from pulling in potentially huge well-known files and using lots of memory.
cc @clokep for info.
> Limit well-known response sizes

- stateresolutionv2.go
This should be faster and more correct, with any luck. We also will now use `int64` for PL sorting in state res v2 specifically.
> Use NewPowerLevelContentFromEvent in getPowerLevelFromAuthEvents

- eventauth.go
> Add presence const

- federationclient.go
Add a method to query remote rooms [Spec](https://spec.matrix.org/v1.1/server-server-api/#post_matrixfederationv1publicrooms)
> Add `POST /publicRooms` for the federation client

- client.go
If a remote server isn't going to SYN-ACK within 5 seconds, it's probably not going to respond anyway. Currently we can spend much longer (possibly the whole 30 seconds of a federation request) just waiting for a TCP acknowledgement which seems suboptimal.
> Enforce 5 second TCP dial timeout for federation

- federationclient.go
- federationtypes.go
Matching https://github.com/matrix-org/dendrite/pull/2232
> Update MSC2946 fields to match spec

- client.go
... since it isn't just used for federation after all.
> Rename `federationTripper` to `destinationTripper`

- event.go
- event_test.go
- eventcontent.go
This defines history visibility constants.
> Define history visibility constants

- edu.go
- event.go
- headeredevent.go
This includes some supporting changes for the Ristretto caching by adding cost estimation for some commonly cached types.
> Ristretto supporting changes

- .github/workflows/tests.yml
- authstate.go
- client.go
- federationclient.go
- redactevent.go
- request.go
- stateresolution.go
Add GHA workflow that runs
- `golangci-lint`
- `go test -race ./...` on GMSL
- `go test ./...` on Dendrite with the new GMSL version
> Add GHA workflow

- eventauth.go
- eventauth_test.go
- stateresolution.go
for https://github.com/matrix-org/dendrite/pull/2791
> Validate auth events are from the same room

- eventauth.go
- eventauth_test.go
- stateresolution.go
- stateresolution_test.go
Fixes the discussed issue with user levels
> Fix `checkUserLevels` and add tests for it

- federationtypes.go
- federationtypes_test.go
Signed-off-by: `Alexander Guz <9241304@gmail.com>`
> Fix behavior for empty host/address (#354)

- authchain.go
- authstate.go
- fclient/federationtypes.go
> Remove .Check() functions; migrate them to GMSL static funcs

- event.go
- eventauth.go
- eventversion.go
- redactevent.go
- redactevent_test.go
To allow custom RoomVersionImpls.
> Make IRoomVersion and use that everywhere

- pdu.go
Needed for some bits of Dendrite.
> Add Unsigned to PDU

- authchain_test.go
- authstate.go
- eventversion.go
- pdu.go
- performjoin.go
Specifically IRoomVersion now returns PDU
> Remove *Event from more places

- authstate_test.go
- backfill_test.go
- event.go
- event_builder.go
- event_test.go
- fclient/federationclient.go
- pdu.go
- performjoin_test.go
- stateresolution_test.go
- stateresolutionv2_test.go
Everything should be talking in terms of `PDU` now.
> Make *Event private

- handleleave.go
- handleleave_test.go
Mostly copy & paste from `MakeJoin`
> Move `MakeLeave` to GMSL

- create.go
- spec/eventtypes.go
Dendrite usage: https://github.com/matrix-org/dendrite/pull/3093
> Move FledglingEvent to gmsl

- event.go
- eventauth.go
- eventcontent.go
- eventcrypto.go
- eventversion.go
- fclient/request.go
- handlejoin.go
- json.go
- keyring.go
- keyring_test.go
> Use functions instead of bools for `IRoomVersion`

- fclient/federationtypes.go
Required for MSC3827: Filtering of /publicRooms by room type
> Add RoomType to PublicRoom struct

- eventauth.go
c.f https://github.com/element-hq/dendrite/pull/3623
> Override fix for v12 rooms
